[tools]
rust = "latest"
golangci-lint = "latest"
go = "latest"

[env]
REDIS_ZERO_DIR = ".local/redis-zero"
REDIS_ONE_DIR = ".local/redis-one"
REDIS_TWO_DIR = ".local/redis-two"
AR_REDIS_SERVERS="unix://$REDIS_ZERO_SOCKET,unix://$REDIS_ONE_SOCKET,unix://REDIS_TWO_SOCKET"
KAFKA_ADRESS="localhost:9092"
REDIS_ADDRESS="localhost:6379"
CLIENT_ID="anarchy"
GROUP_ID="anarchy-1" # pod id in production
REPLICATION_TCP_READ_TIMEOUT_MILLIS=500
LISTEN_ADDRESS="localhost:3679"


[tasks]
lint = "golangci-lint run"

[tasks.client1]
run = """
REDIS_ZERO_SOCKET="$REDIS_ZERO_DIR/.sock"
valkey-cli -s "$REDIS_ZERO_SOCKET" --loglevel verbose
"""

[tasks.kafka]
run = """
docker run -p 9092:9092 apache/kafka:3.9.0
"""

[tasks.'test:valkey-single']
run = """
valkey-server --save ""  --loglevel verbose
"""


[tasks.'test:watch']
run ="""
gotestsum --watch --format standard-verbose ./anarchoredis/replication
"""
